import type { Theme } from '@im-ppt/schema'

/**
 * design-diversity(MIT) PPT 팩 60종 반입 — 색 팔레트 + 타이포 페어링을 우리 Theme으로 매핑.
 * 출처: https://github.com/epoko77-ai/design-diversity (design-packs/ppt-*, tokens.json)
 * 색·폰트 정체성을 그대로 가져온다(개인 전용 플랫폼). 폰트는 웹에서 Google Fonts로 로드.
 */
const S = { display: 46, title: 31, subtitle: 21, body: 16, caption: 12 }

function dv(id: string, name: string, c: Theme['tokens']['colors'], heading: string, body: string, mono: string): Theme {
  return { id, name, tokens: { colors: c, fonts: { heading, body, mono }, fontSizes: S } }
}

export const DESIGN_DIVERSITY_THEMES: Theme[] = [
  dv('ppt-altezza-ultramodern-keynote', 'Altezza 울트라모던 키노트', { primary: '#2EE6A6', secondary: '#9A9CA6', accent: '#2EE6A6', background: '#13141A', surface: '#3A3C46', textPrimary: '#F4F4F6', textSecondary: '#9A9CA6', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Archivo', 'Archivo', 'Courier New'),
  dv('ppt-archival-index-deck', 'Archival Index Deck', { primary: '#33302A', secondary: '#C9C0AC', accent: '#33302A', background: '#EFE9DD', surface: '#F6F2E8', textPrimary: '#33302A', textSecondary: '#7A7468', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Source Serif 4', 'Source Serif 4', 'IBM Plex Mono'),
  dv('ppt-bain-results-deck', '베인 리절츠 덱', { primary: '#CC0000', secondary: '#9CA3AF', accent: '#CC0000', background: '#FFFFFF', surface: '#F4F5F6', textPrimary: '#111827', textSecondary: '#9CA3AF', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Inter', 'Inter', 'Courier New'),
  dv('ppt-bauhaus-geometric', '바우하우스 지오메트릭', { primary: '#D62828', secondary: '#1A1A1A', accent: '#F4C20D', background: '#F0EDE4', surface: '#FFFFFF', textPrimary: '#1A1A1A', textSecondary: '#1A1A1A', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Futura', 'Inter', 'Inter'),
  dv('ppt-bcg-exhibit-deck', 'BCG 익스히빗 덱', { primary: '#177B57', secondary: '#D6DAD8', accent: '#177B57', background: '#FFFFFF', surface: '#F2F4F3', textPrimary: '#1A1A1A', textSecondary: '#5B636E', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'IBM Plex Sans', 'IBM Plex Sans', 'Courier New'),
  dv('ppt-blueprint-schematic-deck', 'Blueprint Schematic Deck', { primary: '#4FC8E8', secondary: '#4FC8E8', accent: '#4FC8E8', background: '#0E1B3D', surface: '#0E1B3D', textPrimary: '#E8EEF7', textSecondary: '#8FA3C8', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Inter', 'Inter', 'Inter'),
  dv('ppt-bold-block-infographic-deck', 'Bold Block Infographic Deck', { primary: '#2A2D34', secondary: '#6B6F76', accent: '#E8A317', background: '#FFFFFF', surface: '#2A2D34', textPrimary: '#2A2D34', textSecondary: '#6B6F76', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Archivo', 'Inter', 'Inter'),
  dv('ppt-botanical-organic', '보태니컬 오가닉', { primary: '#B5654A', secondary: '#7C8B5A', accent: '#7C8B5A', background: '#F2EAD9', surface: '#E5D9C3', textPrimary: '#3A352C', textSecondary: '#3A352C', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Cormorant Garamond', 'Noto Sans KR', 'Cormorant Garamond'),
  dv('ppt-cinematic-keynote-deck', 'Cinematic Keynote Deck', { primary: '#E8B341', secondary: '#262626', accent: '#E8B341', background: '#000000', surface: '#0E0E0E', textPrimary: '#F5F5F7', textSecondary: '#8A8A8E', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Inter', 'Inter', 'Inter'),
  dv('ppt-confident-color-block-deck', 'Confident Color-Block Deck', { primary: '#F0531C', secondary: '#E0E0E0', accent: '#1D4ED8', background: '#FFFFFF', surface: '#FFFFFF', textPrimary: '#141414', textSecondary: '#6E6E6E', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Archivo', 'Archivo', 'Archivo'),
  dv('ppt-consulting-precision-grid', '컨설팅 정밀그리드', { primary: '#0B5FFF', secondary: '#D1D5DB', accent: '#0B5FFF', background: '#FFFFFF', surface: '#F4F5F7', textPrimary: '#1A1A1A', textSecondary: '#6B7280', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Arial', 'Arial', 'Arial'),
  dv('ppt-dark-luxury-keynote', '다크 럭셔리 키노트', { primary: '#C9A36A', secondary: '#8E8A82', accent: '#C9A36A', background: '#0B0B0C', surface: '#1A1A1C', textPrimary: '#EDEAE3', textSecondary: '#8E8A82', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Cormorant Garamond', 'Cormorant Garamond', 'Inter'),
  dv('ppt-dark-tech', '다크모드 테크', { primary: '#3DF5E0', secondary: '#2A2D35', accent: '#9D7BFF', background: '#0C0D10', surface: '#16181D', textPrimary: '#E4E6EB', textSecondary: '#8A8F9A', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Space Grotesk', 'Space Grotesk', 'JetBrains Mono'),
  dv('ppt-data-infographic-heavy', '데이터 인포그래픽 헤비', { primary: '#2563EB', secondary: '#E2E5EA', accent: '#0EA5A4', background: '#F7F8FA', surface: '#FFFFFF', textPrimary: '#1E2229', textSecondary: '#6E7480', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Inter', 'Inter', 'Inter'),
  dv('ppt-editorial-infographic-deck', 'Editorial Infographic Deck', { primary: '#B22B1F', secondary: '#C8C2B4', accent: '#B22B1F', background: '#F6F3EC', surface: '#F6F3EC', textPrimary: '#1C1A17', textSecondary: '#6B655B', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Source Serif 4', 'Inter', 'Courier New'),
  dv('ppt-editorial-magazine', '에디토리얼 매거진', { primary: '#A8312A', secondary: '#C9C5BC', accent: '#A8312A', background: '#FBFAF7', surface: '#FBFAF7', textPrimary: '#1C1B19', textSecondary: '#8A8782', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Playfair Display', 'Source Serif Pro', 'Arial'),
  dv('ppt-editorial-product-deck', 'Editorial Product Deck', { primary: '#B5503A', secondary: '#DAD3C4', accent: '#B5503A', background: '#F7F4EE', surface: '#FCFAF5', textPrimary: '#1F1B16', textSecondary: '#7A7164', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Source Serif 4', 'Inter', 'Inter'),
  dv('ppt-engineered-dark-deck', 'Engineered Dark Deck', { primary: '#8B7BF0', secondary: '#26262C', accent: '#8B7BF0', background: '#0E0E11', surface: '#16161A', textPrimary: '#9CA3AF', textSecondary: '#6B7280', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Inter', 'Inter', 'Inter'),
  dv('ppt-epoch-premium-keynote', 'Epoch 프리미엄 키노트', { primary: '#7FA9C9', secondary: '#9298A4', accent: '#7FA9C9', background: '#1A1E26', surface: '#2C313B', textPrimary: '#E6E8EC', textSecondary: '#9298A4', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Newsreader', 'Inter', 'Inter'),
  dv('ppt-every-golden-grid-keynote', 'Every 골든 그리드 키노트', { primary: '#B5A642', secondary: '#D8D8D2', accent: '#B5A642', background: '#FAFAF8', surface: '#FAFAF8', textPrimary: '#161616', textSecondary: '#6E6E68', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Inter', 'Inter', 'Inter'),
  dv('ppt-expressive-material', '익스프레시브 머티리얼', { primary: '#6750A4', secondary: '#CAC4D0', accent: '#7D5260', background: '#FEF7FF', surface: '#F3EDF7', textPrimary: '#1D1B20', textSecondary: '#1D1B20', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Roboto Flex', 'Roboto Flex', 'Courier New'),
  dv('ppt-expressive-soundwave-deck', 'Expressive Soundwave Deck', { primary: '#FF6B4A', secondary: '#3A3A3A', accent: '#7B3FF2', background: '#121212', surface: '#1E1E1E', textPrimary: '#E8E8E8', textSecondary: '#8A8A8A', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Archivo', 'Archivo', 'Archivo'),
  dv('ppt-folio-portfolio-keynote', 'Folio 포트폴리오 키노트', { primary: '#FF5C35', secondary: '#9A9A9A', accent: '#FF5C35', background: '#F7F7F5', surface: '#FFFFFF', textPrimary: '#141414', textSecondary: '#9A9A9A', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Space Grotesk', 'Space Grotesk', 'Courier New'),
  dv('ppt-glassmorphism', '글래스모피즘', { primary: '#FFFFFF', secondary: '#3A3A52', accent: '#FFFFFF', background: '#7B5BFF', surface: '#7B5BFF', textPrimary: '#1A1A2E', textSecondary: '#3A3A52', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'SF Pro Display', 'SF Pro Display', 'SF Pro Display'),
  dv('ppt-goldman-ir-deck', '골드만 IR 덱', { primary: '#C8A24B', secondary: '#9AA6BC', accent: '#C8A24B', background: '#0A1A33', surface: '#1F3A5F', textPrimary: '#E8E5DE', textSecondary: '#9AA6BC', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Source Serif 4', 'Inter', 'Courier New'),
  dv('ppt-hand-drawn-sketch', '핸드드로운 스케치', { primary: '#E8654A', secondary: '#CFC4AC', accent: '#E0A92E', background: '#F4ECDC', surface: '#F4ECDC', textPrimary: '#2B2724', textSecondary: '#7A7268', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Caveat', 'Pretendard', 'Pretendard'),
  dv('ppt-heritage-luxury-deck', 'Heritage Luxury Deck', { primary: '#A8893E', secondary: '#A8893E', accent: '#A8893E', background: '#EDE6D6', surface: '#F4EFE3', textPrimary: '#3A2E1F', textSecondary: '#8A7C63', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Playfair Display', 'EB Garamond', 'EB Garamond'),
  dv('ppt-hyundai-cinematic-investor-day', '현대차 시네마틱 인베스터데이', { primary: '#66FFFF', secondary: '#1E2A52', accent: '#00D3FD', background: '#101030', surface: '#14274A', textPrimary: '#FFFFFF', textSecondary: '#A8B4C8', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Arial', 'Arial', 'Courier New'),
  dv('ppt-isometric-platform-deck', 'Isometric Platform Deck', { primary: '#3B6FE0', secondary: '#E3E8EF', accent: '#3B6FE0', background: '#EEF1F5', surface: '#FFFFFF', textPrimary: '#1B2330', textSecondary: '#5C6679', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Inter', 'Inter', 'Inter'),
  dv('ppt-kakao-friendly-card-news', '카카오 1Q26 보수 IR', { primary: '#FBE100', secondary: '#BFBFBF', accent: '#FBE100', background: '#F2F2F2', surface: '#FFFFFF', textPrimary: '#000000', textSecondary: '#7F7F7F', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Pretendard', 'Pretendard', 'Courier New'),
  dv('ppt-keynote-minimal-fullbleed', 'Keynote 미니멀 풀블리드', { primary: '#0071E3', secondary: '#86868B', accent: '#0071E3', background: '#FFFFFF', surface: '#FFFFFF', textPrimary: '#1D1D1F', textSecondary: '#86868B', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Helvetica Neue', 'Helvetica Neue', 'Helvetica Neue'),
  dv('ppt-korea-policy-navy', '한국 정책보고서 네이비', { primary: '#1B66C9', secondary: '#C5D2E3', accent: '#E03B3B', background: '#FFFFFF', surface: '#E8F1FB', textPrimary: '#1A1A1A', textSecondary: '#5C6470', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Pretendard', 'Pretendard', 'Pretendard'),
  dv('ppt-kula-minimalist-keynote', 'Kula 미니멀리스트 키노트', { primary: '#B79B86', secondary: '#8C857C', accent: '#B79B86', background: '#EDE8E0', surface: '#FFFFFF', textPrimary: '#4A4540', textSecondary: '#8C857C', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Plus Jakarta Sans', 'Plus Jakarta Sans', 'Plus Jakarta Sans'),
  dv('ppt-luxury-editorial-serif', '럭셔리 에디토리얼 세리프', { primary: '#A8884E', secondary: '#A8884E', accent: '#A8884E', background: '#FAF8F3', surface: '#FAF8F3', textPrimary: '#1A1814', textSecondary: '#8C887E', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Playfair Display', 'Noto Serif KR', 'Inter'),
  dv('ppt-mckinsey-ghost-deck', 'MBB Ghost Deck Framework', { primary: '#1F3A5F', secondary: '#C9CDD3', accent: '#1F3A5F', background: '#FFFFFF', surface: '#FFFFFF', textPrimary: '#1A1A1A', textSecondary: '#7A828F', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Arial', 'Inter', 'Courier New'),
  dv('ppt-mcst-k-culture', '문체부 K-컬처 라벤더', { primary: '#111111', secondary: '#111111', accent: '#111111', background: '#0F1115', surface: '#0F1115', textPrimary: '#111111', textSecondary: '#111111', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Arial', 'Arial', 'Courier New'),
  dv('ppt-memphis-retro-90s', '90s 멤피스 레트로', { primary: '#FF3B7F', secondary: '#1A1A1A', accent: '#00B5C9', background: '#F4ECD8', surface: '#1A1A1A', textPrimary: '#1A1A1A', textSecondary: '#1A1A1A', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Archivo Black', 'Poppins', 'Poppins'),
  dv('ppt-minimal-mono-note', '미니멀 모노 노트', { primary: '#111111', secondary: '#111111', accent: '#111111', background: '#FFFFFF', surface: '#FFFFFF', textPrimary: '#111111', textSecondary: '#8A8A8A', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'JetBrains Mono', 'JetBrains Mono', 'JetBrains Mono'),
  dv('ppt-moef-fiscal-blue', '기획재정부 시네마틱 브리핑', { primary: '#0D1627', secondary: '#A5A5A5', accent: '#0D1627', background: '#0F1115', surface: '#0F1115', textPrimary: '#0D1627', textSecondary: '#A5A5A5', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Arial', 'Arial', 'Courier New'),
  dv('ppt-monochrome-infrastructure-deck', 'Monochrome Infrastructure Deck', { primary: '#000000', secondary: '#000000', accent: '#000000', background: '#FFFFFF', surface: '#F2F2F2', textPrimary: '#000000', textSecondary: '#666666', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Geist', 'Geist', 'Geist Mono'),
  dv('ppt-monochrome-risk', '모노크롬 리스크', { primary: '#0A0A0A', secondary: '#0A0A0A', accent: '#0A0A0A', background: '#FFFFFF', surface: '#E6E6E6', textPrimary: '#0A0A0A', textSecondary: '#767676', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Helvetica Neue', 'Helvetica Neue', 'Helvetica Neue'),
  dv('ppt-motie-slogan-infographic', '산업통상부 슬로건 캘리그래피', { primary: '#111111', secondary: '#5C6470', accent: '#111111', background: '#0F1115', surface: '#0F1115', textPrimary: '#111111', textSecondary: '#5C6470', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Arial', 'Arial', 'Courier New'),
  dv('ppt-msit-ai-three-powers', '과기정통부 정통 정부 라이트', { primary: '#002060', secondary: '#D3DAE6', accent: '#0F41BD', background: '#E7F1FA', surface: '#FFFFFF', textPrimary: '#1C2848', textSecondary: '#3C4860', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Arial', 'Arial', 'Courier New'),
  dv('ppt-naver-integrated-report-award', '네이버 통합보고서 어워드', { primary: '#0A0A0A', secondary: '#7B7B7B', accent: '#0A0A0A', background: '#FFFFFF', surface: '#F5F5F5', textPrimary: '#0A0A0A', textSecondary: '#7B7B7B', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Arial', 'Arial', 'Courier New'),
  dv('ppt-neo-brutalism', '네오브루탈리즘', { primary: '#FF5A36', secondary: '#0A0A0A', accent: '#FFE14D', background: '#FFFFFF', surface: '#FFFFFF', textPrimary: '#0A0A0A', textSecondary: '#0A0A0A', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Archivo Black', 'Arial', 'Arial'),
  dv('ppt-pattern-bold-poster-keynote', 'Pattern 볼드 포스터 키노트', { primary: '#FF4D2E', secondary: '#FFFFFF', accent: '#FF4D2E', background: '#1F3DFF', surface: '#1F3DFF', textPrimary: '#FFFFFF', textSecondary: '#FFFFFF', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Anton', 'Archivo', 'Courier New'),
  dv('ppt-precision-fintech-deck', 'Precision Fintech Deck', { primary: '#5A55E0', secondary: '#E3E8EE', accent: '#5A55E0', background: '#FFFFFF', surface: '#F6F9FC', textPrimary: '#0A2540', textSecondary: '#5C6B7E', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Inter', 'Inter', 'Inter'),
  dv('ppt-print-first-newspaper', '프린트-퍼스트 뉴스페이퍼', { primary: '#A8231B', secondary: '#1C1B17', accent: '#A8231B', background: '#F4F1E8', surface: '#F4F1E8', textPrimary: '#1C1B17', textSecondary: '#1C1B17', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Playfair Display', 'Noto Serif KR', 'Inter'),
  dv('ppt-prismatic-dark-deck', 'Prismatic Dark Diagram Deck', { primary: '#22D3EE', secondary: '#1E2336', accent: '#D946EF', background: '#0B0E1A', surface: '#141A2E', textPrimary: '#E8EAF0', textSecondary: '#8A90A6', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Inter', 'Inter', 'JetBrains Mono'),
  dv('ppt-samsung-ir-restrained', '삼성전자 IR 절제', { primary: '#0028A8', secondary: '#111111', accent: '#0028A8', background: '#0F1115', surface: '#0F1115', textPrimary: '#111111', textSecondary: '#111111', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Arial', 'Manrope', 'Courier New'),
  dv('ppt-skt-interactive-ai-pyramid', 'SKT 인터랙티브 AI 피라미드', { primary: '#0023C3', secondary: '#D7D7D7', accent: '#0023C3', background: '#FFFFFF', surface: '#E4EEFB', textPrimary: '#000000', textSecondary: '#595757', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Arial', 'Arial', 'Courier New'),
  dv('ppt-soft-pastel-system-deck', 'Soft Pastel System Deck', { primary: '#C9BEEB', secondary: '#8A8492', accent: '#A6DAC9', background: '#FAF7F4', surface: '#FFFFFF', textPrimary: '#3A3640', textSecondary: '#8A8492', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Quicksand', 'Nunito Sans', 'Nunito Sans'),
  dv('ppt-startup-pitch-colorful', '스타트업 피치 컬러풀', { primary: '#5B5BFF', secondary: '#E5E7F0', accent: '#FF5C8A', background: '#FFFFFF', surface: '#F4F6FF', textPrimary: '#15161B', textSecondary: '#15161B', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Poppins', 'Inter', 'Courier New'),
  dv('ppt-strategy-navy-deck', 'Strategy Navy Deck', { primary: '#2563EB', secondary: '#C7D0DD', accent: '#2563EB', background: '#FFFFFF', surface: '#F1F4F9', textPrimary: '#14213D', textSecondary: '#5B6472', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'PT Serif', 'Inter', 'Inter'),
  dv('ppt-swiss-editorial-bold', '스위스 에디토리얼 볼드', { primary: '#FF4A1C', secondary: '#111111', accent: '#0047FF', background: '#F2F0EB', surface: '#111111', textPrimary: '#111111', textSecondary: '#111111', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Archivo Black', 'Inter', 'Inter'),
  dv('ppt-unikorea-peace-coexistence', '통일부 한반도 평화공존', { primary: '#105FD2', secondary: '#111111', accent: '#F59751', background: '#050829', surface: '#050829', textPrimary: '#111111', textSecondary: '#111111', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Pretendard', 'Pretendard', 'Pretendard'),
  dv('ppt-vivid-gradient-future', '비비드 그라디언트 퓨처', { primary: '#D11D8E', secondary: '#FFFFFF', accent: '#2563EB', background: '#0F1115', surface: '#0F1115', textPrimary: '#FFFFFF', textSecondary: '#FFFFFF', success: '#34D399', warning: '#FBBF24', error: '#F87171' }, 'Space Grotesk', 'Inter', 'Space Grotesk'),
  dv('ppt-vivid-gradient-infographic-deck', 'Vivid Gradient Infographic Deck', { primary: '#7C3AED', secondary: '#ECE8F4', accent: '#FB6F5C', background: '#FBFAFE', surface: '#FFFFFF', textPrimary: '#211B33', textSecondary: '#7C7591', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Poppins', 'Poppins', 'Poppins'),
  dv('ppt-warm-hospitality-deck', 'Warm Hospitality Deck', { primary: '#F4625F', secondary: '#EDE8E4', accent: '#F4625F', background: '#FFFFFF', surface: '#FBF7F4', textPrimary: '#2B2B2E', textSecondary: '#79767A', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Poppins', 'Poppins', 'Poppins'),
  dv('ppt-warm-minimal-diagram-deck', 'Warm Minimal Diagram Deck', { primary: '#C2693F', secondary: '#3D3528', accent: '#C2693F', background: '#F2EBDF', surface: '#FBF7EF', textPrimary: '#3D3528', textSecondary: '#8A8170', success: '#16A34A', warning: '#CA8A04', error: '#DC2626' }, 'Work Sans', 'Work Sans', 'Work Sans'),
]

/** 팩 id → 갤러리 카테고리 */
export const DESIGN_DIVERSITY_CATEGORY: Record<string, string> = {
  'ppt-altezza-ultramodern-keynote': 'minimal',
  'ppt-archival-index-deck': 'minimal',
  'ppt-bain-results-deck': 'business',
  'ppt-bauhaus-geometric': 'creative',
  'ppt-bcg-exhibit-deck': 'business',
  'ppt-blueprint-schematic-deck': 'tech',
  'ppt-bold-block-infographic-deck': 'creative',
  'ppt-botanical-organic': 'creative',
  'ppt-cinematic-keynote-deck': 'minimal',
  'ppt-confident-color-block-deck': 'creative',
  'ppt-consulting-precision-grid': 'business',
  'ppt-dark-luxury-keynote': 'minimal',
  'ppt-dark-tech': 'tech',
  'ppt-data-infographic-heavy': 'tech',
  'ppt-editorial-infographic-deck': 'creative',
  'ppt-editorial-magazine': 'creative',
  'ppt-editorial-product-deck': 'creative',
  'ppt-engineered-dark-deck': 'tech',
  'ppt-epoch-premium-keynote': 'minimal',
  'ppt-every-golden-grid-keynote': 'minimal',
  'ppt-expressive-material': 'creative',
  'ppt-expressive-soundwave-deck': 'tech',
  'ppt-folio-portfolio-keynote': 'minimal',
  'ppt-glassmorphism': 'creative',
  'ppt-goldman-ir-deck': 'business',
  'ppt-hand-drawn-sketch': 'creative',
  'ppt-heritage-luxury-deck': 'creative',
  'ppt-hyundai-cinematic-investor-day': 'business',
  'ppt-isometric-platform-deck': 'tech',
  'ppt-kakao-friendly-card-news': 'business',
  'ppt-keynote-minimal-fullbleed': 'minimal',
  'ppt-korea-policy-navy': 'business',
  'ppt-kula-minimalist-keynote': 'minimal',
  'ppt-luxury-editorial-serif': 'creative',
  'ppt-mckinsey-ghost-deck': 'minimal',
  'ppt-mcst-k-culture': 'business',
  'ppt-memphis-retro-90s': 'creative',
  'ppt-minimal-mono-note': 'minimal',
  'ppt-moef-fiscal-blue': 'business',
  'ppt-monochrome-infrastructure-deck': 'minimal',
  'ppt-monochrome-risk': 'minimal',
  'ppt-motie-slogan-infographic': 'business',
  'ppt-msit-ai-three-powers': 'tech',
  'ppt-naver-integrated-report-award': 'business',
  'ppt-neo-brutalism': 'creative',
  'ppt-pattern-bold-poster-keynote': 'minimal',
  'ppt-precision-fintech-deck': 'tech',
  'ppt-print-first-newspaper': 'creative',
  'ppt-prismatic-dark-deck': 'tech',
  'ppt-samsung-ir-restrained': 'minimal',
  'ppt-skt-interactive-ai-pyramid': 'tech',
  'ppt-soft-pastel-system-deck': 'creative',
  'ppt-startup-pitch-colorful': 'creative',
  'ppt-strategy-navy-deck': 'business',
  'ppt-swiss-editorial-bold': 'creative',
  'ppt-unikorea-peace-coexistence': 'business',
  'ppt-vivid-gradient-future': 'creative',
  'ppt-vivid-gradient-infographic-deck': 'creative',
  'ppt-warm-hospitality-deck': 'creative',
  'ppt-warm-minimal-diagram-deck': 'minimal',
}

/** 이 팩들이 쓰는 폰트 패밀리(웹 Google Fonts 로딩용) */
export const DESIGN_DIVERSITY_FONTS: string[] = [
  'Anton',
  'Archivo',
  'Archivo Black',
  'Arial',
  'Caveat',
  'Cormorant Garamond',
  'Courier New',
  'EB Garamond',
  'Futura',
  'Geist',
  'Geist Mono',
  'Helvetica Neue',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'Inter',
  'JetBrains Mono',
  'Manrope',
  'Newsreader',
  'Noto Sans KR',
  'Noto Serif KR',
  'Nunito Sans',
  'PT Serif',
  'Playfair Display',
  'Plus Jakarta Sans',
  'Poppins',
  'Pretendard',
  'Quicksand',
  'Roboto Flex',
  'SF Pro Display',
  'Source Serif 4',
  'Source Serif Pro',
  'Space Grotesk',
  'Work Sans',
]
